development:
  adapter: postgresql
  database: music_player_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: music_player_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: music_player_production
  pool: 5
  timeout: 5000
