#seeeeeeed

Song.create(title: 'Be Sweet', artist: 'Japanese Breakfast', artist_about: 'Japanese Breakfast is the solo musical project of American musician Michelle Zauner (born March 29, 1989). Under the alias, Zauner has released three studio albums: Psychopomp (2016), Soft Sounds from Another Planet (2017) and Jubilee (2021).', image_link: 'https://i.ibb.co/hcnpXqb/japanese-breakfast-be-sweet.jpg', video_link: 'https://www.youtube.com/embed/2ZfcZEIo6Bw?autoplay=1', categories: ["alternative", "pop", "indie"])
Song.create(title: 'In My Room', artist: 'Frank Ocean', artist_about: 'Frank Ocean (born October 28, 1987)[3][4] is an American singer, songwriter, record producer, rapper, photographer, and visual artist. Recognized for his idiosyncratic musical style, introspective and elliptical songwriting, and wide vocal range, Ocean is among the most acclaimed artists of his generation.', image_link: 'https://i.ibb.co/ZfQ1RqB/frank-ocean-in-my-room.jpg', video_link: 'https://www.youtube.com/embed/PtvlmOsNV4E?autoplay=1', categories: ["alternative R&B", "soul", "psychedelic pop"])
Song.create(title: 'Ya Just Need 2 Believe in Yaself', artist: 'Folamour', artist_about: 'Part of the recent renaissance of young French House and Disco producers, Folamour is an artist with a deep love for all music. His passion is demonstrated across the many edits, remixes and original records he produces.', image_link: 'https://i.ibb.co/GT4pvbh/folamour-believe-in-yaself.jpg', video_link: 'https://www.youtube.com/embed/Vd1veZGlxMg?autoplay=1', categories: ["dance", "electronic"] )
Song.create(title: 'Yonaguni', artist: 'Bad Bunny', artist_about: 'Benito Antonio Martínez Ocasio (born March 10, 1994), known by his stage name Bad Bunny, is a Puerto Rican rapper, singer, and songwriter. His music is often defined as Latin trap and reggaeton, but he has incorporated various other genres into his music, including rock, bachata, and soul. He is also known for his deep, slurred vocal style and his eclectic fashion sense. Throughout his career, Bad Bunny has frequently collaborated with artists such as J Balvin, Farruko, Residente, Arcángel, Jhay Cortez, and Daddy Yankee.', image_link: 'https://i.ibb.co/dbnCssH/bad-bunny-yonaguni.jpg', video_link: 'https://www.youtube.com/embed/doLMt10ytHY?autoplay=1', categories: ["latin trap", "reggaeton"])

Song.create(title: 'A Lovers Holiday', artist: 'Change', artist_about: 'Change is an Italian-American post-disco group formed in Bologna, Italy, in 1979 by businessman and executive producer Jacques Fred Petrus (1948–1987) and Mauro Malavasi (born 1957). They were heavily influenced by the disco band Chic. The current incarnation of the group formed in 2018.', image_link: 'https://i.ibb.co/TvH65CH/change-a-lovers-holiday.jpg', video_link: 'https://www.youtube.com/embed/gbxnRTcb458?autoplay=1', categories: ["disco", "R&B", "soul"] )
Song.create(title: 'Dragonball Durag', artist: 'Thundercat', artist_about: 'In 2016, Thundercat won a Grammy for Best Rap/Sung Performance for his work on the track "These Walls" from To Pimp a Butterfly. In 2020, Thundercat released his fourth studio album titled It is What It is, which earned him a Grammy Award for Best Progressive R&B Album.', image_link: 'https://i.ibb.co/s5NBLsj/thundercat-dragonball-durag.jpg', video_link: 'https://www.youtube.com/embed/ormQQG2UhtQ?autoplay=1', categories: ["R&B", "soul", "jazz"])
Song.create(title: 'Naive Melody', artist: 'Talking Heads', artist_about: 'Talking Heads were an American rock band formed in 1975 in New York City and active until 1991.', image_link: 'https://i.ibb.co/4Mv4Hrn/talking-heads-naive-melody.jpg', video_link: 'https://www.youtube.com/embed/HldHtBxNK6k?autoplay=1', categories: ["new wave", "post-punk", "art-pop"])
Song.create(title: 'Show Me How', artist: 'Men I Trust', artist_about: 'Men I Trust is a Canadian indie band from Montreal, Quebec. Formed in 2014, the band consists of Jessy Caron, Dragos Chiriac and Emmanuelle Proulx. The group self-released its early work and subsequently has released music on Canadian indie label Return To Analog.', image_link: 'https://i.ibb.co/M95T0NL/men-i-trust-show-me-how.jpg', video_link: 'https://www.youtube.com/embed/OZRYzH0Q0pU?autoplay=1', categories: ["indie", "dream-pop"])

Song.create(title: 'Give Me The Night', artist: 'George Benson', artist_about: 'George Washington Benson (born March 22, 1943)[3] is an American guitarist, singer, and songwriter. He began his professional career at the age of 19 as a jazz guitarist.', image_link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyZb_IkSgpMLlFhFPVqL_Xb7T1g1Z19KvsPtLQeQDXuk7_Yg34GJOnprPWl51u6k_WXtc&usqp=CAU', video_link: 'https://www.youtube.com/embed/Omnpu8mzX4c?autoplay=1', categories: ["funk", "soul"])
Song.create(title: 'Starry Night', artist: 'Peggy Gou', artist_about: 'Peggy Gou is a Berlin-based South Korean DJ. She has released seven EPs on record labels including Ninja Tune and Phonica. In 2019, she launched her own independent record label, Gudu Records, and released a DJ-Kicks compilation, DJ-Kicks: Peggy Gou, on !k7 Records.', image_link: 'https://upload.wikimedia.org/wikipedia/commons/d/da/Peggy_Gou_2019.jpg', video_link: 'https://www.youtube.com/embed/kD0en6bbJPI?autoplay=1', categories: ["dance", "electronic", "house"])
Song.create(title: 'Only You', artist: 'Steve Monite', artist_about: 'Steve Monite is a Nigerian singer and songwriter best known for the 1984 Afro-boogie song, "Only You" (which had several versions and was produced by the music guru Chief Tony Okoroji for EMI records in Nigeria[1]) which was the hit track and the album title.[2]', image_link: 'https://f4.bcbits.com/img/0014723024_10.jpg', video_link: 'https://www.youtube.com/embed/L-2CyO8pc0E?autoplay=1', categories: ["dance", "funk", "soul"])
Song.create(title: 'Ski', artist: 'Young Stoner Life, Young Thug, Gunna', artist_about: 'Slime Language 2 is a collaborative compilation album by American record label YSL Records and American rappers Young Thug and Gunna, two signees from the label with the former rapper being its leader.', image_link: 'https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2021%2F04%2Fyoung-thug-gunna-ski-music-video-3.jpg?w=1600&cbr=1&q=90&fit=max', video_link: 'https://www.youtube.com/embed/92j7Ep_RPhM" title="YouTube video player?autoplay=1', categories: ["hip-hop", "trap"])

Song.create(title: 'Nightmares on Wax Boiler Room London DJ Set', artist: 'Nightmares on Wax', artist_about: 'An extended daytime set from the legendary Nightmares On Wax.', image_link: 'https://scenenoise.com/Content/Articles/Big_image/637065500909891654_NOWWakeUpCall.jpg', video_link: 'https://www.youtube.com/embed/Q692lHFaLVM?autoplay=1', categories: ['dj-set', 'house', 'electronic'])
Song.create(title: 'Honey Dijon Boiler Room x Sugar Mountain 2018 DJ Set', artist: 'Honey Dijon', artist_about: 'Revel in the magic of the best. Honey Dijon stopping time with her Sugar Mountain set in Melbourne.', image_link: 'https://scenenoise.com/Content/Articles/Big_image/39626788-ff5a-4205-a38a-068e4255e833.png', video_link: 'https://www.youtube.com/embed/m_qewI-1cEs?autoplay=1', categories: ['dj-set', 'house', 'electronic'])
Song.create(title: 'Afro Cuban/Latin Jazz on Vinyl with Salt Cathedral', artist: 'Salt Cathedral', artist_about: 'Salt Cathedral is a band from Bogotá, Colombia, and currently based in Brooklyn, New York, in the United States. The band consists of Juliana Ronderos and Nicolás Losada.', image_link: 'https://images.squarespace-cdn.com/content/v1/5344b090e4b0dccfc34c6374/1557099875871-6KB9KABX55FANH427EKQ/SaltCathedral1.jpg', video_link: 'https://www.youtube.com/embed/aC8KjG9SM30?autoplay=1', categories: ['dj-set', 'latin', 'jazz'])
Song.create(title: 'DJ Maseo (De La Soul) | Boiler Room London DJ Set', artist: 'De La Soul', artist_about: 'An extended daytime set from the legendary Nightmares On Wax.', image_link: 'https://media.npr.org/assets/img/2013/12/29/74961791_wide-11d4e7bb8dc7df509b4569b88836098e1c6ea8e0.jpg', video_link: 'https://www.youtube.com/embed/v1Uji6CHTao?autoplay=1', categories: ['dj-set', 'house', 'soul', 'funk'])

Song.create(title: 'Curumim Chama Cunhatã Que Vou Contar', artist: 'Jorge Ben Jor', artist_about: 'Jorge Duilio Lima Menezes (born March 22, 1939) is a Brazilian popular musician, performing under the stage name Jorge Ben Jor since the 1980s, though commonly known by his former stage name Jorge Ben. His characteristic style fuses samba, funk, rock and bossa nova with lyrics that blend humor and satire with often esoteric subject matter.', image_link: 'https://thevinylfactory.com/wp-content/uploads/2020/08/Jorge-Ben-razil-Funk-Power-Brazilian-Funk-Samba-Soul-7-BOX-SET-soul-jazz-462x280.jpg', video_link: 'https://www.youtube.com/embed/nn5E9iLqzg8?autoplay=1', categories: ['funk', 'brazilian', 'samba'])

Song.create(title: 'Love Reigns', artist: 'Mall Grab', artist_about: 'Jordon Alexander is an Australian producer and Disc jockey/DJ based in London, UK. He releases music as Mall Grab, under his own name, and as part of the formation Mystik Menn (alongside DJ Haus). Having a background in skateboarding, Alexanders stage name is a reference to the mocking term Skateboarding/skateboarders use for holding your skateboard by the truck instead of the deck (a mall grab), which is supposedly looked down upon. His productions mainly fall within the House music/house and techno genres, and Alexander is known for being one of the leading figures in the Outsider house/lo-fi house genre that emerged in 2016.', image_link: 'https://www.dummymag.com/wp-content/uploads/2019/04/avatars-000584806266-67oe1i-t500x500.jpg', video_link: 'https://www.youtube.com/embed/2-rbRymAB4U?autoplay=1', categories: ['house', 'electronic'])
Song.create(title: 'Encerrada', artist: 'Reyna Tropical', artist_about: 'Reyna Tropical is Fabi Reyna and Sumohair, they met for the first time in Nashville, Tennesse on behalf of Redbull Music Academys Bass Camp at Bonnaroo. They got into the studio the same day they met, recorded a track that would later inspire "Reyna Tropical".', image_link: 'https://www.lataco.com/wp-content/uploads/Cred_-Alejandro-Berber-2-scaled.jpg', video_link: 'https://www.youtube.com/embed/1jDOxt9vWMo?autoplay=1', categories: ['latin', 'indie','tropical'])
Song.create(title: 'Lumberjack', artist: 'Tyler The Creator', artist_about: 'Tyler Gregory Okonma, better known as Tyler, The Creator (born March 6, 1991) is an American rapper, record producer, and music video director. He is the leader and co-founder of the since-disbanded Los Angeles collective Odd Future. Tyler is currently signed to Sony Music Entertainment, Columbia Records, and his own record label, Odd Future Records.', image_link: 'https://variety.com/wp-content/uploads/2021/06/Screen-Shot-2021-06-17-at-11.29.55-AM.png', video_link: 'https://www.youtube.com/embed/R4Y7JIQlv20?autoplay=1', categories: ['hip-hop', 'rap'])




Song.create(title: 'Burna Boy: NPR Music Tiny Desk Concert', artist: 'Burna Boy', artist_about: "Watch Burna Boy play 'Gbona', 'Wetin Man Go Do', 'Dangote' and 'Ye' at the Tiny Desk.", image_link: 'https://media.architecturaldigest.com/photos/613f942ad12eac1f56ce925a/16:9/w_2560%2Cc_limit/BURNA-SHOOT-FOR-AD2890.jpg', video_link: 'https://www.youtube.com/embed/xaaYgVRZTnE?autoplay=1', categories: ['world', 'afrobeats', 'dancehall'])

Song.create(title: 'Guest Mix: Peruvian Chicha/Cumbia with Cal Jader', artist: 'Cal Jader', artist_about: "Cal Jader is one of the musical activists behind London Latin cultural protagonists Movimientos and co-host of one of London's finest tropical / global bass parties Love Carnival. With his trademark blend of latin beats, carnival rhythms and fresh global sounds he is helping to soundtrack London's underground music scene with regular sets across the capital, as well as around the UK and Europe.", image_link: 'https://soundsandcolours.com/static/2017/12/dj-cal-jader-movimientos-best-of-2017.jpg', video_link: 'https://www.youtube.com/embed/6GwdWSx8v0c?autoplay=1', categories: ['dj-set', 'latin', 'cumbia'])


Comment.create(song_id: 1, content: 'This rocks')
Comment.create(song_id: 2, content: 'On repeat.')
Comment.create(song_id: 3, content: 'Thats my jam.')