#seeeeeeed

Song.create(title: 'Be Sweet', artist: 'Japanese Breakfast', artist_about: 'Japanese Breakfast is the solo musical project of American musician Michelle Zauner (born March 29, 1989). Under the alias, Zauner has released three studio albums: Psychopomp (2016), Soft Sounds from Another Planet (2017) and Jubilee (2021).', image_link: 'https://i.scdn.co/image/5f81d58a6a1de44b28148055a4fadfe46ab38bcd', video_link: 'https://www.youtube.com/embed/2ZfcZEIo6Bw')
Song.create(title: 'In My Room', artist: 'Frank Ocean', artist_about: 'Frank Ocean (born October 28, 1987)[3][4] is an American singer, songwriter, record producer, rapper, photographer, and visual artist. Recognized for his idiosyncratic musical style, introspective and elliptical songwriting, and wide vocal range, Ocean is among the most acclaimed artists of his generation.', image_link: 'https://d2u3kfwd92fzu7.cloudfront.net/catalog/artwork/gallery/1076/WT_F_2015_038_02_10.001.L.jpg', video_link: 'https://www.youtube.com/embed/PtvlmOsNV4E')
Song.create(title: 'Ya Just Need 2 Believe in Yaself', artist: 'Folamour', artist_about: 'Part of the recent renaissance of young French House and Disco producers, Folamour is an artist with a deep love for all music. His passion is demonstrated across the many edits, remixes and original records he produces.', image_link: 'https://4c79id2ej5i11apui01ll2wc-wpengine.netdna-ssl.com/wp-content/uploads/2019/05/Folamour-755x437.jpg', video_link: 'https://www.youtube.com/embed/Vd1veZGlxMg' )
Song.create(title: 'Yonaguni', artist: 'Bad Bunny', artist_about: 'Bad Bunny bebe', image_link: 'https://thefader-res.cloudinary.com/private_images/w_760,c_limit,f_auto,q_auto:eco/RUIZ_BadBunny_22_V2_o4ytkj/shirt-hot-topic-overalls-tommy-hilfiger-vintage-necklace-and-sunglasses-bad-bunny-s-own.jpg', video_link: 'https://www.youtube.com/embed/doLMt10ytHY')
Song.create(title: 'A Lovers Holiday', artist: 'Change', artist_about: 'Change is an Italian-American post-disco group formed in Bologna, Italy, in 1979 by businessman and executive producer Jacques Fred Petrus (1948–1987) and Mauro Malavasi (born 1957). They were heavily influenced by the disco band Chic. The current incarnation of the group formed in 2018.', image_link: 'https://upload.wikimedia.org/wikipedia/en/3/3d/Sharing_your_love_change_album.jpg', video_link: 'https://www.youtube.com/embed/gbxnRTcb458')
Song.create(title: 'Dragonball Durag', artist: 'Thundercat', artist_about: 'In 2016, Thundercat won a Grammy for Best Rap/Sung Performance for his work on the track "These Walls" from To Pimp a Butterfly. In 2020, Thundercat released his fourth studio album titled It is What It is, which earned him a Grammy Award for Best Progressive R&B Album.', image_link: 'https://cdn.mos.cms.futurecdn.net/3ND6WpyK6dPa8mfwwqijPM-1200-80.jpg', video_link: 'https://www.youtube.com/embed/ormQQG2UhtQ')
Song.create(title: 'Naive Melody', artist: 'Talking Heads', artist_about: 'Talking Heads were an American rock band formed in 1975 in New York City and active until 1991.', image_link: 'https://pencilsqueezer.files.wordpress.com/2018/10/screen-shot-2018-10-23-at-13-30-26.png', video_link: 'https://www.youtube.com/embed/HldHtBxNK6k')
Song.create(title: 'Show Me How', artist: 'Men I Trust', artist_about: 'Men I Trust is a Canadian indie band from Montreal, Quebec. Formed in 2014, the band consists of Jessy Caron, Dragos Chiriac and Emmanuelle Proulx. The group self-released its early work and subsequently has released music on Canadian indie label Return To Analog.', image_link: 'https://front.imposemagazine.com/wp-content/uploads/2019/05/4580d1270c19a39aa088d2528a99e519.jpg', video_link: 'https://www.youtube.com/embed/OZRYzH0Q0pU')

Comment.create(song_id: 1, content: 'This rocks')
Comment.create(song_id: 2, content: 'On repeat.')
Comment.create(song_id: 2, content: 'Thats my jam.')

